version: "3.9"
services:
    postgres:
        image: postgres:14
        container_name: achievement-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            PGDATA: /var/lib/postgresql/data/pgdata # Explicitly set data directory
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata # Match PGDATA path
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
            interval: 5s
            timeout: 5s
            retries: 20
        ports:
            - "5432:5432"
        restart: "unless-stopped"
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: achievement-web
        ports:
            - "8501:8501"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        command: >
            sh -c "
            echo 'Waiting for postgres...' &&
            sleep 5 &&
            echo 'Running database initialization...' &&
            python src/database/init_db.py &&
            echo 'Starting Streamlit...' &&
            streamlit run src/main.py"
        restart: "unless-stopped"

volumes:
    postgres_data:
        name: achievement-postgres_data
