version: "3.9"
services:
    postgres:
        image: postgres:14
        container_name: achievement-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
        security_opt:
            - no-new-privileges:true
        read_only: true
        tmpfs:
            - /tmp
            - /var/run/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
            interval: 5s
            timeout: 5s
            retries: 20
        ports:
            - "5432:5432"
        restart: unless-stopped

    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: achievement-web
        security_opt:
            - no-new-privileges:true
        read_only: true
        tmpfs:
            - /tmp
        ports:
            - "8501:8501"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        restart: unless-stopped
        command: >
            sh -c "
            echo 'Waiting for postgres...' &&
            sleep 5 &&
            echo 'Running database initialization...' &&
            python src/database/init_db.py &&
            echo 'Starting Streamlit...' &&
            streamlit run src/main.py"

volumes:
    postgres_data:
        name: achievement-postgres_data
